aaaaaaaaaaAAAAAA
Stellarica/Stellarica pull request #127
Opened 2023-03-14 14:35 UTC by HyperSoop

This pr:

- adds a 1-tick delay to player teleportation on ship movement in hopes to slightly smooth out ship movement
- "fixes" a scheduler misbehaviour that comes with this
- fixes how right and left are mixed up again

2023-03-14 14:36 UTC, HyperSoop commented
wait a bit i'll try something

2023-03-14 14:39 UTC, HyperSoop commented
ok thats better

2023-03-14 17:06 UTC, trainb0y requested changes

2023-03-14 17:06 UTC, trainb0y commented on server/paper/src/main/kotlin/net/stellarica/server/crafts/Craft.kt
> +			Tasks.sync(
why the newline? Not really an issue, just curious.

2023-03-14 17:06 UTC, trainb0y commented on server/paper/src/main/kotlin/net/stellarica/server/crafts/Craft.kt
> +						val destination =
this indentation is... funky

2023-03-14 17:06 UTC, trainb0y commented on server/paper/src/main/kotlin/net/stellarica/server/crafts/Craft.kt
> +			Tasks.sync(
Might be better to use `syncDelay` as it makes it more clear there's a delay.

2023-03-14 17:10 UTC, HyperSoop commented on server/paper/src/main/kotlin/net/stellarica/server/crafts/Craft.kt
> +						val destination =
i have no idea, i've just copy pasted some code and it didn't error somehow so here we are  
can you fix those minor issues you find yourself? it says maintainers are allowed to edit

2023-03-14 17:12 UTC, HyperSoop commented on server/paper/src/main/kotlin/net/stellarica/server/crafts/Craft.kt
> +			Tasks.sync(
Isn't this kinda different? `sync(block)` schedules it for the next tick, and `syncDelay(1, block)` schedules it 1 tick ahead

i suppose it's not

2023-03-14 17:12 UTC, trainb0y commented on server/paper/src/main/kotlin/net/stellarica/server/crafts/Craft.kt
> +			Tasks.sync(
You can set a delay of 0

2023-03-14 17:12 UTC, trainb0y commented on server/paper/src/main/kotlin/net/stellarica/server/crafts/Craft.kt
> +						val destination =
I guess, yeah. I'll work on it later.

2023-03-14 17:13 UTC, HyperSoop commented on server/paper/src/main/kotlin/net/stellarica/server/crafts/Craft.kt
> +			Tasks.sync(
What would that do?

2023-03-14 17:16 UTC, trainb0y commented on server/paper/src/main/kotlin/net/stellarica/server/crafts/Craft.kt
> +			Tasks.sync(
Exact same thing as `sync`, it just makes what's happening a little clearer

2023-03-14 17:18 UTC, HyperSoop commented on server/paper/src/main/kotlin/net/stellarica/server/crafts/Craft.kt
> +			Tasks.sync(
(why should sync exist at all then!?)

i think i'll also try syncDelay 1 then, since sync seems fine and delay 2 is too much maybe delay 1 would be just right

2023-03-14 17:19 UTC, trainb0y commented on server/paper/src/main/kotlin/net/stellarica/server/crafts/Craft.kt
> +			Tasks.sync(
> (why should sync exist at all then!?)
It's left over from Star Legacy's code, which I ~~blatantly stole~~ acquired for my own purposes.

2023-03-14 17:20 UTC, HyperSoop commented on server/paper/src/main/kotlin/net/stellarica/server/crafts/Craft.kt
> +			Tasks.sync(
~~sync - deprecated(forRemoval)~~

2023-03-18 08:39 UTC, HyperSoop commented
i just renamed the branch lmao github

2023-03-19 15:35 UTC, closed without merging